### ISSUE TITLE
Bluetooth won't work

### ISSUE THREAD

**Issue by cryptono** [lopaka/instructions#12]
I tried your new bluetooth setup instructions but it didn't work.
Bluetooth still won't work.
What should I do?

**Comment by karanvb** [comment]
Did this method works. I want to try with my windows tablet which has Intel atom processor.

**Comment by cryptono** [comment]
It works now! But: You need to make the linux kernel as described in "Kernel changes for audio support" to use bluetooth, otherwise it won't work. Maybe you could add that to your instructions. :-) I am so glad Ubuntu is now fully supported on Asus, great work, UbuntuForums. :+1:

**Comment by evilhawk00** [comment]
For those using Kali linux 2019.1 , after following the instructions to enable btattach service, opening the bluetooth from setting panel does not work....seems a bug. Use `systemctl enable bluetooth` fix this issue.
