### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by brooksyx** [lopaka/instructions#3]
Hey, thanks for putting this guide together. Can't wait to get ubuntu working fully on this little guy. Could care less about the keyboard keys but obviously sound and wifi are a must. Any updates on that front in the pas couple months? Thanks!

**Comment by lopaka** [comment]
Hello,

I've added a notice on the page on Dec 11, 2014 that I've returned the device because of the lack of hardware support.  Thanks for looking at the page and good luck.
