### ISSUE TITLE
Can't find vmlinuz and Grub won't work

### ISSUE THREAD

**Issue by catalincraciun** [lopaka/instructions#4]
Hello, I am trying to install linux on a Vensmile. I can get to the Grub screen but I can't find vmlinuz... I found it in /casper but is called vmlinuz.efi. Can't I use that? Also at the next step what to use? /dev/sdb? I made my usb using Rufus. I would appreciate if you could help me. Thank you.

**Comment by lopaka** [comment]
I do not have access to a Vensmile.  Are you following the [instructions](https://github.com/lopaka/instructions/blob/master/ubuntu-14.10-install-asus-x205ta.md) on installing on an X205TA?  If so, where is it failing?

**Comment by catalincraciun** [comment]
I have solved my problems by disabling Fast boot. You can close this now. Thank you.
