### ISSUE TITLE
Grub install: filesystem unknown on selecting kernel

### ISSUE THREAD

**Issue by RonanPresle** [lopaka/instructions#5]
Hi,

Thanks for this nice tutorial. It helped me a lot, but I still have a problem while installing grub.

On running this command :

    linux (hd1,gpt2)/boot/vmlinuz-3.16-0-23-generic root=/dev/mmcblk0p2 reboot=pci,force

I got the error `error: unknown filesystem` 

Do you have any clues of how to solve this error? Thanks

**Comment by lopaka** [comment]
Page has been deprecated in favor for instructions for Ubuntu 16.04 LTS.

**Comment by hipunk** [comment]
I'm sorry, I do not know that.
