### ISSUE TITLE
How to set up wireless to my specific tablet?

### ISSUE THREAD

**Issue by digdig** [lopaka/instructions#8]
I have a similar situation as described here, follow your command, I've successfully create a bootable usb. However, when setting the wireless, which is very critical, I don't know how to proceed, your command is:

```
sudo cp /sys/firmware/efi/efivars/nvram-74b00bd9-805a-4d61-b51f-43268123d113 /lib/firmware/brcm/brcmfmac43340-sdio.txt
sudo modprobe -v -r brcmfmac
sudo modprobe -v brcmfmac
```

How to change is to my machine? I'm totally a newbie so how do I check something like  `nvram-74b00bd9-805a-4d61-b51f-43268123d113` and replace it with my specifications? should `brcmfmac43340-sdio.txt` be changed too? Please give me some guidance...

**Comment by lopaka** [comment]
Hello @digdig,
That file happens to be the config file for the brcmfmac driver to get wifi working correctly on the X205TA laptop.  I would suggest looking into what wifi device you have in your table and check for drivers specificlly for that device.

Good Luck.

**Comment by digdig** [comment]
Because I can't check the wireless device name of my tablet, can't find on net. However, I can find the driver name on windows it requires, the name is `Realtek RTL8723BS Wireless LAN 802.11n SDIO Network Adapter` . I also see the wiki of arch:https://wikidevi.com/wiki/List_of_Wi-Fi_Device_IDs_in_Linux. I can find only `8723BE`. 

How to proceed?

**Comment by lopaka** [comment]
There does appear to be some development on supporting the RTL8723BS: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1581711
I would suggest following comment [#18](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1581711/comments/18) to build and install it.

Good Luck

**Comment by digdig** [comment]
Should I copy the source file into the install usb and type the following lines:

```
cd rtl8723as
make
sudo make install
sudo depmod -a
sudo modprobe r8723bs
```

After this, is the driver properly installed? Do I need something like your code:

```
sudo cp /sys/firmware/efi/efivars/nvram-74b00bd9-805a-4d61-b51f-43268123d113 /lib/firmware/brcm/brcmfmac43340-sdio.txt
sudo modprobe -v -r brcmfmac
sudo modprobe -v brcmfmac
```

**Comment by lopaka** [comment]
You will need to compile the code, which is what `make` does. But to compile, you need to install `build-essential linux-headers-generic git`.  Basically, you will need to run what's in step [#18](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1581711/comments/18) as I mentioned above.  However to do that you will need to have some type of network connection to your tablet, perhaps a usb wifi adapter if possible.  You may be able to run some of the steps on the system that you are creating the usb drive with, but you will have to try it out and do some investigating.

**Comment by digdig** [comment]
Does the package build-essential linux-headers-generic not in the iso file? 

What I mean is to git clone the code using my PC, and copy the source code to the usb drive, then `make` in the tablet while installing.

However if that two package not exist in the official iso, i may need a usb wifi...

**Comment by digdig** [comment]
I've fixed the wifi problem, do I need to check `Download updates while installing Lubuntu`?

**Comment by digdig** [comment]
![20160901_001938](https://cloud.githubusercontent.com/assets/5459093/18141722/43832a9c-6fed-11e6-80aa-3d3bfc495bb8.jpg)
![20160901_022725](https://cloud.githubusercontent.com/assets/5459093/18141721/43812d00-6fed-11e6-8fb9-7a999c390df7.jpg)

It seems that even I don't check that box, the installer will download something from the net, however, the installation still fails, any ideas?

**Comment by lopaka** [comment]
Unfortunately, I do not know what the issue is without investigating.  It says 'no installation candidate'. Perhaps you are using a old version of Ubuntu 16.04?  Usually, I would do 'apt update' when such a message appears to get current packages.

**Comment by digdig** [comment]
I will try what you said, today I got a usb-wifi with me, hope this will make the installation straight forward...
